[build]
  command = "cd frontend && npm ci && npm run build"
  functions = "functions"
  publish = "frontend/build"  # Make it relative to root (was absolute—cleaner this way)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200